Test_Shell/TestShell.cpp
Test_Shell/TestShellScript.cpp
Test_Shell/TestShellTest.cpp

This commit includes skeleton code for TestShell class, TestShellScript class, and gmock test.

[test] Add base code for test

---

AClass_SSD.sln
Test_Shell/TestShell.cpp
Test_Shell/TestShell.h
Test_Shell/TestShellTest.cpp
Test_Shell/Test_Shell.vcxproj
Test_Shell/Test_Shell.vcxproj.filters

TestShell 헤더파일 추가
write, fullwrite, exit api 구현

[feature] Add TestShell API and TC

---

Test_Shell/TestShell.cpp
Test_Shell/TestShell.h
Test_Shell/TestShellTest.cpp

read/fullRead/help 함수에 대한 기본 선언과 테스트 코드입니다.

[feature] add read/fullRead/help test

---

Test_Shell/TestShell.cpp
Test_Shell/TestShell.h
Test_Shell/TestShellTest.cpp

read 결과 type이 int로 되어있던 것을 uint32_t로 수정하였습니다.

[bugfix] fix read return type

---

Test_Shell/TestShell.cpp
Test_Shell/TestShell.h
Test_Shell/TestShellTest.cpp
Test_Shell/Test_Shell.vcxproj
Test_Shell/Test_Shell.vcxproj.filters

- Change function name to be more readable
- Change TDD code to call real write() function.

[refac] refactoring parsing command

---

AClass_SSD/Data.cpp
AClass_SSD/Data.h
AClass_SSD/DataTest.cpp
AClass_SSD/main.cpp
AClass_SSD/test_output.txt

data 헤더와 cpp 파일 그리고 test 파일 입니다.

[feature] data 헤더,cpp,test

---

AClass_SSD/AClass_SSD.vcxproj
AClass_SSD/AClass_SSD.vcxproj.filters
AClass_SSD/Data.cpp
AClass_SSD/Data.h
AClass_SSD/DataInterface.h
AClass_SSD/SSDData.cpp
AClass_SSD/SSDData.h
AClass_SSD/SSDDataTest.cpp

SSD Read하는 부분 입니다. 코드 리뷰 부탁드립니다. 감사합니다.

Feature/ssd/ssd Read 기능 구현

---

AClass_SSD.sln
Inc/ITestShell.h
TestShell_Test/TestShellMock.cpp
TestShell_Test/TestShellMock.h
TestShell_Test/TestShellTest.cpp
TestShell_Test/TestShell_Test.vcxproj
TestShell_Test/TestShell_Test.vcxproj.filters
TestShell_Test/packages.config
Test_Shell/TestShell.cpp
Test_Shell/TestShell.h
Test_Shell/TestShellApp.cpp
Test_Shell/TestShellApp.h
Test_Shell/TestShellScript.h
Test_Shell/Test_Shell.vcxproj
Test_Shell/main.cpp

- Mock을 위한 interface class를 추가하였습니다.
- 이에따라 TC로 Mock을 활용할 수 있도록 변경하였습니다.
- 전체 tc pass를 위해 나머지 커맨드도 dummy 코드로 추가하였습니다.

[feature] Apply TestShell interface and Mock class for test

---

AClass_SSD/SSDDataTest.cpp

[bugfix] fix build error due to incorrect parameter naming

HOTFIX!!! 빠른 리뷰 부탁드립니다.

---

Inc/ITestShell.h
TestShell_Test/TestShellMock.cpp
TestShell_Test/TestShellMock.h
TestShell_Test/TestShellTest.cpp
Test_Shell/TestShell.cpp
Test_Shell/TestShell.h
Test_Shell/TestShellApp.cpp

- invalid param TC 추가
- return value enum화
- handleCommand function 미구현 부분 추가
- token parsing 하는 부분 수정

[refac] change parameter passing to handleCommand

---

TestShell_Test/TestShellTest.cpp

read/write 시 command 잘못 준 경우 error return 체크 테스트입니다. 
exit 시 command parsing 성공여부 테스트입니다.

[Test] refactoring 진행하며 날아간 test case 복구

---

AClass_SSD/AClass_SSD.vcxproj
AClass_SSD/AClass_SSD.vcxproj.filters
AClass_SSD/Command.cpp
AClass_SSD/Command.h
AClass_SSD/CommandTest.cpp

[feature] implement initial Command class

---

Inc/ITestShell.h
TestShell_Test/ITestShell.cpp

command error 체크해주는 로직을 함수화하였습니다.

[Refac] handleCommand 함수 클린코드작업

---

Test_Shell/TestShellApp.cpp

shell에서 enter만 입력시 프로그램 죽는 에러 수정
fixed 화면

[bugfix] shell에서 enter만 입력시 프로그램 죽는 에러 수정

---

Inc/ITestShell.h
TestShell_Test/ITestShell.cpp

handleCommand
isWriteDataValid
isWriteCommandValid
isReadCommandValid
isValidLBA
isCommandValid
함수들 paramter const화

[refactor] handleCommand함수와 command error check함수 parameter const화

---

AClass_SSD/main.cpp

[feature] modify main to make ssd executable

---

Inc/ITestShell.h
TestShell_Test/ITestShell.cpp

-매직넘버 define으로 정리
- 범위 체크(숫자 혹은 알파벳대문자) 로직을
숫자는 std의 isdigit() 함수 활용
알파벳대문자는 isdigit() 함수와 레벨을 맞추기위하여 새로 구현하였음

[Refactor] clean isWriteDataValid 함수

---

Inc/ITestShell.h
TestShell_Test/ITestShell.cpp

기존 함수들(아래기술)과의 통일성을 위하여 함수명 변경하였습니다.
isWriteDataValid
isWriteCommandValid
isReadCommandValid
isFullwriteCommandValid
isCommandValid

[Refactor] 함수명 isValidLBA() --> isLBAValid() 변경

---

AClass_SSD/Command.cpp
AClass_SSD/Command.h
AClass_SSD/FileTextIO.cpp
AClass_SSD/FileTextIO.h
AClass_SSD/SSDController.cpp
AClass_SSD/SSDController.h
TestShell_Test/ITestShell.cpp

함수 내에서 값을 변경하지 않는 parameter들에 대해
const화 진행하였습니다.

[refactor] 함수 파라미터 const 작업

---

AClass_SSD/SSDControllerTest.cpp

대문자 출력으로 변경한 후 테스트 페일되는 것 수정하였습니다.

[bugfix] fix test fail because change print hex number to uppercase

---

Inc/ITestShell.h
TestShell_Test/ITestShell.cpp
TestShell_Test/TestShellTest.cpp
Test_Shell/TestShellDevice.cpp

erase/erase_range 커맨드 입력시 처리하도록
구현하였습니다.
TC 통과하였습니다. SSD와의 궁합은 추후 확인하여야합니다.

[feature] erase/erase_range 커맨드 입력 처리 구현

---

AClass_SSD/AClass_SSD.vcxproj
AClass_SSD/AClass_SSD.vcxproj.filters
AClass_SSD/CommandBuffer.cpp
AClass_SSD/CommandBuffer.h

commandbuffer 기본 함수 구현하였습니다.
텍스트파일 가져와서 버퍼 초기화
버퍼에 커맨드 추가하는 기능
버퍼 커맨드를 텍스트파일로 만드는 것

[feature] add initial CommandBuffer class

---

AClass_SSD/Command.cpp
AClass_SSD/Command.h
AClass_SSD/CommandTest.cpp
AClass_SSD/FileTextIO.cpp
AClass_SSD/FileTextIO.h
AClass_SSD/FileTextIOInterface.h
AClass_SSD/FileTextIOTest.cpp
AClass_SSD/SSDController.cpp
AClass_SSD/SSDController.h
AClass_SSD/SSDControllerInterface.h
AClass_SSD/SSDControllerTest.cpp
AClass_SSD/main.cpp

SSD 구조 통합
SSD Erase 기능 추가 및 대문자 hex 저장 적용

[feature] SSD 통합 및 Erase function

---

Test_Shell/Logger.cpp
Test_Shell/Logger.h

log파일들만 단독으로 관리하기 위하여 생성한 log 파일들을
log directory에 저장(directory가 없으면생성)하도록 변경

[refactor] log파일을 log디렉토리 안으로 생성

---

AClass_SSD/Command.cpp
AClass_SSD/Command.h
AClass_SSD/CommandTest.cpp
AClass_SSD/FileTextIO.cpp
AClass_SSD/FileTextIO.h
AClass_SSD/main.cpp

- Write/Erase 명령어는 버퍼에 저장
- F(Flush) 명령으로 일괄 수행
- Read 명령은 즉시 수행
- buffer 폴더 구조 및 상태 파일 구성

[feature] SSD 명령어 CommandBuffer 연동 기능 완료

---

AClass_SSD/CommandBuffer.cpp
AClass_SSD/CommandBuffer.h

merge 로직 버그 수정하였습니다
commandvalue 생성자 빌드 에러 수정하였습니다.
CommandValue(char chCommad, int LBA, uint32_t value) 생성자 추가하였습니다.
풀 스트링 가져오는 함수 getCommandStr() 추가하였습니다.

[feature] implement getCommandStr() function

---

AClass_SSD/AClass_SSD.vcxproj
AClass_SSD/AClass_SSD.vcxproj.filters
AClass_SSD/CommandBuffer.cpp
AClass_SSD/CommandBufferTest.cpp

commandBuffer 테스트 추가하였습니다.
lba가 0인 경우 동작안하는 부분 수정하였습니다.

[TEST] add commandBuffer class Test

---

Interface/ITestShell.cpp
Test_Shell/TestShellDevice.cpp

return 값 잘못 해주고 있는 함수 return 수정
return type이 uint32이나 -리턴 하고 있는 것 수정

bugfix: fix return value & type

---

Interface/ITestShell.cpp
Test_Shell/Logger.cpp
Test_Shell/Logger.h
Test_Shell/TestShellApp.cpp
Test_Shell/TestShellApp.h
Test_Shell/TestShellDevice.cpp

[refac] 불필요한 주석이나 코드 제거

---

AClass_SSD/Command.cpp
AClass_SSD/Command.h
AClass_SSD/CommandTest.cpp
AClass_SSD/main.cpp

- `Command` 클래스에 Strategy 패턴과 Interface Segregation 원칙 적용  
- `ICommandExecutor` 인터페이스 도입으로 실행 흐름 추상화
- 명령어 등록 및 실행을 `std::function` 기반으로 구현하여 가독성과 확장성 향상
- `main.cpp`에서 Command 생성 로직을 Factory 함수로 분리  
- 의존성 주입 및 테스트 용이성 확보
- `CommandBuffer`를 통한 Fast Read 기능 통합  
- READ 시 버퍼에 같은 LBA에 대한 WRITE/ERASE 명령이 있는 경우 NAND 접근 없이 처리
- `CommandTest.cpp` 테스트 코드 수정  
- Fast Read 처리 흐름 및 예외 케이스에 대한 테스트 반영

[refactor] Command 구조 개선 및 Fast Read 기능 통합

---

AClass_SSD/CommandBuffer.cpp
AClass_SSD/CommandBufferTest.cpp

E 95 5
W 98 0xFFFF1111
W 97 0xFFFF1111
W 99 0xFFFF1111
위와 같은 경우 아래로 되도록
E 95 2
W 98 0xFFFF1111
W 97 0xFFFF1111
W 99 0xFFFF1111

[bugfix] modify removeOverwrittenSingleErase
